#apiVersion: v1
#kind: Secret
#metadata:
#    name: dingo-es-tls
#    namespace: default
#data:
#    tls.crt: base64 encoded cert
#    tls.key: base64 encoded key
#type: kubernetes.io/tls
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
    name: dingo-es-cert-gcp-managed
spec:
    domains:
    - k8es.ingest.bindiego.com
    - k8es.client.bindiego.com
    - k8na.bindiego.com
