apiVersion: batch/v1
kind: Job
metadata:
  name: command-demo-never-restart-job
  labels:
    purpose: demonstrate-command
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: command-demo-container
        image: debian
        command: ["/bin/sh"]
        args: ["-c", "i=1; while true; do echo `date`; echo -n job1:; echo $i; i=$((i+1)); sleep 30; done; exit 0"]
      restartPolicy: Never
